spring.application.name: spring-boot-admin

server:
  servlet.context-path: /app-admin
  tomcat.redirect-context-root: false
  forward-headers-strategy: native
  shutdown: immediate

spring:
  boot:
    admin:
      monitor:
        status-interval: 30000
        status-lifetime: 30000
        info-interval: 3m
        info-lifetime: 3m

      instance-auth:
        enabled: false

#debug: true
#logging:
#  level:
#    # Spring Security OAuth2 core classes
#    org.springframework.security.oauth2: DEBUG
#
#    # Client registration and authentication flow
#    org.springframework.security.oauth2.client: TRACE
#
#    # Token handling and validation
#    org.springframework.security.oauth2.jwt: DEBUG
#    org.springframework.security.oauth2.jose: DEBUG
#
#    # Web client requests
#    org.springframework.web.client.RestTemplate: DEBUG
#
#    # HTTP traffic (very verbose)
#    org.springframework.web: DEBUG
#    org.apache.http: DEBUG
#
#    # Keycloak specific (if needed)
#    org.keycloak: DEBUG